# Generated by Django 2.2.24 on 2021-11-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_book_movie"),
        ("users", "0003_user_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_book",
                to="home.Book",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_car",
                to="home.Car",
            ),
        ),
    ]
